---
output:
  pdf_document:
    latex_engine: xelatex
geometry: top=1.5cm, bottom=1cm, left=1.5cm, right=1.5cm
header-includes:
  - \usepackage{fontspec}
  - \usepackage{amsmath}
  - \usepackage{amssymb}
---

```{r setup, include=FALSE}
#Limpiamos entorno
rm(list = ls(all.names = TRUE))

gc() #Liberamos memoria

knitr::opts_chunk$set(
	error = F,
	fig.align = "center",
	fig.dim = c(5, 3),  
	message = FALSE,
	warning = FALSE
)


# Librerias a usar
library(ggplot2)
library(kableExtra)
library(boot)
library(patchwork)
library(dplyr)
library(tidyr)
library(readr) #Leer arcuhivos csv y txt
library(readxl)

```

```{r datos}

computosDistritales <- read_csv("C:/Users/ferna/Documents/Diplomado_Data_Sience/Proyectos/ProyectoModulo4/Data/2018_SEE_GOB_YUC_CAS.csv")
names(computosDistritales)[4] <- "ID_DIST_LOC"


conteoRapido <- read_excel("C:/Users/ferna/Documents/Diplomado_Data_Sience/Proyectos/ProyectoModulo4/Data/ConteoRapidoMUESTRA_CASILLAS_YUCATAN.xlsx")
names(conteoRapido)[c(2, 9)] <- c("ID_ESTADO", "LN")



casillas <- read_delim("C:/Users/ferna/Documents/Diplomado_Data_Sience/Proyectos/ProyectoModulo4/Data/CASILLAS.txt",
                       delim = "|",
                       skip = 1,           # para saltar la línea "188"
                       col_names = TRUE,
                       trim_ws = TRUE,
                       show_col_types = FALSE)
names(casillas)[1] <- "ID_ESTADO"






```

```{r}
df_resultados <- data.frame(
  casilla = character(),
  nombre = character(),
  media = numeric(),
  low = numeric(),
  high = numeric(),
   stringsAsFactors = FALSE
)





# Agrega una nueva file a nuestro df, Resultados
nueva_fila_resultados <- function(casilla, candidato, media, low, high) {
  fila <- data.frame(
    casilla = casilla,
    nombre = candidato,
    media = media,
    low = low,
    high = high,
    stringsAsFactors = FALSE
  )
  
  df_resultados <- rbind(df_resultados, fila)
  return(df_resultados)
}


```


```{r}
head(conteoRapido)

head(computosDistritales)

head(casillas)
```
```{r}
length(casillas)
```


```{r}
id_unico_casilla <- function(BD){
  paste0("A", formatC(BD$ID_ESTADO, width = 2, flag = 0),
         formatC(BD$ID_DIST_LOC, width = 2, flag = 0), 
         formatC(BD$SECCION, width = 4, flag = 0),
         BD$TIPO_CASILLA,
         formatC(BD$ID_CASILLA, width = 2, flag = 0),
         formatC(BD$EXT_CONTIGUA, width = 2, flag = 0))
}

#Creando los IDs unicos para casilla 

conteoRapido$ID_UC <- id_unico_casilla(conteoRapido)

computosDistritales$ID_UC <- id_unico_casilla(computosDistritales)

casillas$ID_UC <- id_unico_casilla(casillas)


```


```{r}
#Creando la propocion de conteos rapidos por candidato

computosDistritales$MVD   <- computosDistritales$PAN + computosDistritales$PAN_MC + computosDistritales$MC
computosDistritales$MSR   <- computosDistritales$PRI + computosDistritales$PVEM + computosDistritales$`NA` + 
                              computosDistritales$PRI_PVEM + computosDistritales$PRI_NA + 
                              computosDistritales$PVEM_NA + computosDistritales$PRI_PVEM_NA
computosDistritales$JEZC  <- computosDistritales$PRD
computosDistritales$JJDM  <- computosDistritales$PT + computosDistritales$MORENA + computosDistritales$ES + 
                              computosDistritales$PT_MORENA + computosDistritales$PT_ES + 
                              computosDistritales$MORENA_ES + computosDistritales$PT_MORENA_ES
computosDistritales$CNR   <- computosDistritales$NUM_VOTOS_CAN_NREG
computosDistritales$NULOS <- computosDistritales$NUM_VOTOS_NULOS
computosDistritales$TOTAL <- computosDistritales$TOTAL_VOTOS


casillas300 <- conteoRapido %>%
  left_join(computosDistritales, by = c("ID_UC" = "ID_UC")) %>%
  select(ID_UC, MVD, MSR, JEZC, JJDM, NULOS, CNR, TOTAL) %>%
  filter(!is.na(MVD)) %>%
  mutate(
    MVD   = MVD / TOTAL,
    MSR   = MSR / TOTAL,
    JEZC  = JEZC / TOTAL,
    JJDM  = JJDM / TOTAL,
    CNR   = CNR,
    NULOS = NULOS,
    TOTAL = TOTAL
  ) %>%
  filter(!is.na(MVD | MSR | JEZC | JJDM | CNR | NULOS | TOTAL))


casillas180 <- casillas %>%
  left_join(computosDistritales, by = c("ID_UC" = "ID_UC")) %>%
 select(
    ID_UC, MVD.y, MSR.y, JEZC.y, JJDM.y, CNR.y, NULOS.y, TOTAL.y
  ) %>%
  mutate(
    MVD   = MVD.y / TOTAL.y,
    MSR   = MSR.y / TOTAL.y,
    JEZC  = JEZC.y / TOTAL.y,
    JJDM  = JJDM.y / TOTAL.y,
    CNR   = CNR.y,
    NULOS = NULOS.y,
    TOTAL = TOTAL.y
  ) %>%  select(ID_UC, MVD, MSR, JEZC, JJDM, NULOS, CNR, TOTAL) %>%
  filter(!is.na(MVD))


filtro <- casillas180 %>% left_join( casillas300, by = "ID_UC") %>%
select(
    ID_UC, MVD.x, MSR.x, JEZC.x, JJDM.x, CNR.x, NULOS.x, TOTAL.x
) %>%
   mutate(
    MVD   = MVD.x,
    MSR   = MSR.x,
    JEZC  = JEZC.x,
    JJDM  = JJDM.x,
    CNR   = CNR.x,
    NULOS = NULOS.x,
    TOTAL = TOTAL.x
  ) %>%  select(ID_UC, MVD, MSR, JEZC, JJDM, NULOS, CNR, TOTAL) %>%
  filter(!is.na(MVD))
  

#interseccion <- inner_join(casillas188, casillas300, by = "ID_UC")
```


```{r}
casillas300
```
```{r}
library(visdat)

vis_dat(casillas300)

```


```{r}
filtro
vis_dat(filtro)
```



```{r Bootstrap}

candidatos <- c("MVD", "MSR", "JEZC", "JJDM")
casillasVotos <- c("188", "300", "Filtro")

set.seed(123454)


 
bootstrapCandidatos <- function(df, candidato, tamaño) {
  # Elimina NA del candidato
  vector_limpio <- df[[candidato]][!is.na(df[[candidato]])]

  valores <- numeric(tamaño)
  for (i in 1:tamaño) {
    muestra <- sample(vector_limpio, size = length(vector_limpio), replace = TRUE)
    valores[i] <- mean(muestra)
  }

  meanBoot <- mean(valores)
  sdBoot <- sd(valores)

  salida <- list(
    media = meanBoot,
    low   = meanBoot - 1.96 * sdBoot,
    high  = meanBoot + 1.96 * sdBoot,
    sd    = sdBoot
  )
  return(salida)
}

 



```

```{r}
reps = 10000
for (i in casillasVotos) {
  for (candidato in candidatos) {
    if (i == "188") {
      resultado <- bootstrapCandidatos(casillas180, candidato, reps)
    } else if (i == "300") {
      resultado <- bootstrapCandidatos(casillas300, candidato, reps)
    } else {
       resultado <- bootstrapCandidatos(filtro, candidato, reps)
    }
    
    df_resultados <- nueva_fila_resultados(i, candidato, resultado$media, resultado$low, resultado$high)
  }
}
```








```{r}
df_resultados <- df_resultados %>%
  mutate(
    media = media * 100,
    low = low * 100,
    high = high * 100
  )

df_resultados 
```



```{r}
c188 <- df_resultados %>%
  filter(casilla == "188") %>%
  select(nombre, media, low, high)

c300 <- df_resultados %>%
  filter(casilla == "300") %>%
  select(nombre, media, low, high)

cf <- df_resultados %>%
  filter(casilla == "Filtro") %>%
  select(nombre, media, low, high)

c188

library(esquisse)
```




```{r}
esquisse::esquisser(c188)
```

```{r}
ggplot(c188) +
  aes(x = nombre, y = media) +
  geom_bar(stat = "summary", fun = "sum", fill = "#0C4C8A") +
  labs(title = "188 casillas") +
  theme_minimal()

ggplot(c300) +
  aes(x = nombre, y = media) +
  geom_bar(stat = "summary", fun = "sum", fill = "#2e7d32") +
  labs(title = "300 casillas") +
  theme_minimal()

ggplot(cf) +
  aes(x = nombre, y = media) +
  geom_bar(stat = "summary", fun = "sum", fill = "#00838f") +
  labs(title = "Filtro Casilllas casillas") +
  theme_minimal()


```



```{r}
ggplot(cf, aes(x = nombre)) +
  geom_errorbar(aes(ymin = low, ymax = high), width = 0.2, colour = "#B22222", size = 1.2) +
  geom_point(aes(y = media), colour = "#0072B2", size = 4) +
  theme_minimal() +
  labs(
    title = "Intervalos de confianza - Casilla Filtro",
    x = "Candidato",
    y = "Porcentaje estimado (%)"
  )


ggplot(c188, aes(x = nombre)) +
  geom_errorbar(aes(ymin = low, ymax = high), width = 0.2, colour = "#B22222", size = 1.2) +
  geom_point(aes(y = media), colour = "#0072B2", size = 4) +
  theme_minimal() +
  labs(
    title = "Intervalos de confianza - Casilla Filtro",
    x = "Candidato",
    y = "Porcentaje estimado (%)"
  )


ggplot(c300, aes(x = nombre)) +
  geom_errorbar(aes(ymin = low, ymax = high), width = 0.2, colour = "#B22222", size = 1.2) +
  geom_point(aes(y = media), colour = "#0072B2", size = 4) +
  theme_minimal() +
  labs(
    title = "Intervalos de confianza - Casilla Filtro",
    x = "Candidato",
    y = "Porcentaje estimado (%)"
  )

```


